const PDFDocument = require('pdfkit');

const generateAssessmentPDF = (userData, assessmentData) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: 'A4',
                margin: 50
            });

            // Collect the chunks of the PDF
            const chunks = [];
            doc.on('data', chunk => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));

            // Add content to PDF
            // Header
            doc.fontSize(25)
               .text('Fit-With-AI Assessment Report', { align: 'center' })
               .moveDown();

            // User Info
            doc.fontSize(16)
               .text('User Profile', { underline: true })
               .moveDown();

            doc.fontSize(12);
            doc.text(`Name: ${userData.fullName}`);
            doc.text(`Email: ${userData.email}`);
            doc.moveDown();

            // Assessment Details
            doc.fontSize(16)
               .text('Assessment Results', { underline: true })
               .moveDown();

            doc.fontSize(12);
            
            // Fitness Goals
            doc.text('Fitness Goals:', { underline: true });
            doc.text(assessmentData.fitnessGoals)
               .moveDown();

            // Activity Level
            doc.text('Activity Level:', { underline: true });
            doc.text(assessmentData.activityLevel)
               .moveDown();

            // Medical Conditions
            doc.text('Medical Conditions:', { underline: true });
            doc.text(assessmentData.medicalConditions || 'None reported')
               .moveDown();

            // Health Metrics
            if (assessmentData.healthMetrics) {
                doc.text('Health Metrics:', { underline: true });
                Object.entries(assessmentData.healthMetrics).forEach(([key, value]) => {
                    doc.text(`${key}: ${value}`);
                });
                doc.moveDown();
            }

            // Recommendations
            doc.fontSize(16)
               .text('Recommendations', { underline: true })
               .moveDown();

            doc.fontSize(12)
               .text('Based on your assessment, we recommend:')
               .moveDown();

            // Add recommendations based on assessment data
            const recommendations = generateRecommendations(assessmentData);
            recommendations.forEach(rec => {
                doc.text(`• ${rec}`);
            });

            // Footer
            doc.moveDown()
               .fontSize(10)
               .text('Generated by Fit-With-AI', { align: 'center' })
               .text(new Date().toLocaleDateString(), { align: 'center' });

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
};

const generateRecommendations = (assessmentData) => {
    const recommendations = [];

    // Add general recommendations
    recommendations.push('Schedule regular check-ups with your healthcare provider');
    recommendations.push('Stay hydrated by drinking at least 8 glasses of water daily');
    
    // Add specific recommendations based on activity level
    if (assessmentData.activityLevel === 'Beginner') {
        recommendations.push('Start with low-impact exercises 2-3 times per week');
        recommendations.push('Focus on building basic strength and endurance');
    } else if (assessmentData.activityLevel === 'Intermediate') {
        recommendations.push('Incorporate a mix of cardio and strength training 4-5 times per week');
        recommendations.push('Consider adding HIIT workouts to your routine');
    } else if (assessmentData.activityLevel === 'Advanced') {
        recommendations.push('Maintain a diverse workout routine with progressive overload');
        recommendations.push('Include recovery days to prevent overtraining');
    }

    // Add recommendations based on medical conditions
    if (assessmentData.medicalConditions) {
        recommendations.push('Consult with your healthcare provider before starting any new exercise routine');
        recommendations.push('Monitor your condition during workouts and adjust intensity as needed');
    }

    return recommendations;
};

module.exports = {
    generateAssessmentPDF
}; 